apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudcart-frontend
  namespace: cloudcart

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloudcart-frontend

  template:
    metadata:
      labels:
        app: cloudcart-frontend

    spec:
      containers:
      - name: cloudcart-frontend

        image: 114171679862.dkr.ecr.us-east-1.amazonaws.com/cloudcart-frontend:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 3000